source 'https://rubygems.org'

gem 'rails',                   '6.0.0'
gem 'bcrypt',                  '3.1.11'
gem 'faker',                   '1.6.6'
gem 'puma',                    '3.4.0'
gem 'uglifier',                '3.0.0'
gem 'coffee-rails',            '5.0.0'
gem 'jquery-rails',            '4.3.5'
gem 'turbolinks',              '5.0.0'
gem 'jbuilder',                '2.9.1'

gem 'nokogiri',                '>= 1.10.4'
gem 'rack',                    '>= 2.0.6'
gem 'loofah',                  '>= 2.2.3'
gem 'rubyzip',                 '>= 1.2.2'

group :development, :test do
  gem 'sqlite3', '1.3.13'
  gem 'byebug',  '9.0.0', platform: :mri
end

group :development do
  gem 'web-console',           '3.1.1'
  gem 'listen',                '3.1.5'
  gem 'spring',                '1.7.2'
  gem 'spring-watcher-listen', '2.0.0'
end

group :test do
  gem 'rails-controller-testing', '1.0.4'
  gem 'minitest-reporters',       '1.1.9'
  gem 'guard',                    '2.13.0'
  gem 'guard-minitest',           '2.4.4'
end

group :production do
  gem 'pg',   '0.18.4'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
